### ISSUE TITLE
Seems overkill.

### ISSUE THREAD

**Issue by NDevTK** [masasron/chrome-bandit#1]
This requires ruby and a debugger permission when it can just be read directly,
https://www.nirsoft.net/utils/web_browser_password.html even has a CLI.

**Comment by masasron** [comment]
The way passwords are stored on Windows and macOS is different.

On Windows, Chrome uses the Data Protection API (DPAPI) to bind your passwords to your user account and store them on disk encrypted with a key only **accessible to processes running as the same logged on user.**

On macOS, Chrome is storing the credentials in “Login Data” in the Chrome users profile directory, but encrypted on disk with a key that is then stored in the user’s Keychain. Keychain uses [Access Control Lists](https://developer.apple.com/documentation/security/keychain_services/access_control_lists) that control which apps have access to keychain items in macOS, which makes it way harder to get the passwords.

As far as I know, there are no open-source tools for extracting passwords from Google Chrome on macOS.
Also, Ruby comes preinstalled on macOS. 😉

**Comment by NDevTK** [comment]
Ah makes more sense now that said it should be as direct as possible the current way requires the website to be designed in a certain way and the target needs to be known.

I think it would be better to scrape the data from chrome://settings/passwords
If the keychain prevents non-root users from reading its contents and keyloggers are not allowed.

**Comment by NDevTK** [comment]
Also Google is moving to optional permissions with manifest v3 it should be only requests permission for websites it needs the password for.

**Comment by NDevTK** [comment]
Might try to create a PR if the debugger API allows you to open chrome://settings/passwords as then you get the private API.
chrome.passwordsPrivate.getSavedPasswordList();

**Comment by NDevTK** [comment]
After further review it does not seem overkill for macOS,
If the internal chrome password page requires login before it can export passwords this seems like the best to do it :)

Feature requests:
- iframe support (all_frames: true)
- listing passwords (should be possible by scraping chrome://settings/passwords)
- not being controlled by website design (create form via content script)
- multiple credentials in autofill

**Comment by masasron** [comment]
1. Yup, that's definitely a bug 
2. I'm pretty sure you can not execute scripts on `chrome://settings/passwords` using an extension. Also, `chrome://settings/passwords` does the right thing - requiring user authentication before showing the plain text password.
3. I was thinking of something like that, I looked at the `Login Data` file and saw chrome does store the "selector" for `username_element` and `password_element` of each login. However, it's not so clear what is the format used to generate this selector and hence how to convert it back to a form. (Would take some work...)
4. The current script collects all inputs which are not hidden and basically gives you the diff, before and after autofill.

I'm not sure I want to put that much effort into making a robust solution for that, I mainly wanted to show this can be done on macOS.
