### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by MilesYM** [masasron/chrome-bandit#3]
Hi I'm trying to run it on my mac but I'm getting errors whatever command I try to run:

chrome-bandit list --chrome gives ERROR: no records

I am trying to access passwords that were saved before using time machine on my mac, I lost everything and cannot retrieve them. Maybe the encryption key changed when using the new mac?

Thank you for your help and for the library, it's cool

**Comment by masasron** [comment]
Hi @MilesYM, this is not a recovery tool, it's just a tool to programmatically extract the passwords Chrome has already access to.

The error indicates the program was not able to retrieve the password since it does not exist or inaccessible.
